languageCode = "en-us"
languageName = "English"
displayName = ":flag-us:"
isoCode = "en-us"
weight = 1
rtl = false

title = "The Coach Cave"
 #logo = "img/logo.jpg"
description = "Personal blog, mainly for writeups"
copyright = "&copy; 2024 Afonso Coutinho"

dateFormat = "2 January 2006"

[params.author]
  name = "Afonso Coutinho"
  image = "img/avatar.jpg"
  headline = "Msc Cyber-Security"
  bio = "Msc Cyber-Security"
  links = [
    { github = "https://github.com/coachtinho" },
    { linkedin = "https://linkedin.com/in/joão-coutinho-a5b20a20a" }
  ]
